name: CD Front-End Main

on:
  workflow_dispatch:

jobs:
  ci:
    name: CI Workflow Main FrontEnd
    uses: ./.github/workflows/ci-frontend.yml
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: johnbeynon/render-deploy-action@master
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_FRONT }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
