name: CD Front-End Main

on:
  workflow_dispatch:

jobs:
  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-frontend.yml

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debugging Step
        run: echo "${{ secrets.RENDER_SERVICE_ID_FRONT }}  ${{ secrets.RENDER_API_KEY }}"

      - name: Deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_FRONT }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
